// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=../mock/mock_patient_controller.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockPatientController is a mock of PatientController interface.
type MockPatientController struct {
	ctrl     *gomock.Controller
	recorder *MockPatientControllerMockRecorder
	isgomock struct{}
}

// MockPatientControllerMockRecorder is the mock recorder for MockPatientController.
type MockPatientControllerMockRecorder struct {
	mock *MockPatientController
}

// NewMockPatientController creates a new mock instance.
func NewMockPatientController(ctrl *gomock.Controller) *MockPatientController {
	mock := &MockPatientController{ctrl: ctrl}
	mock.recorder = &MockPatientControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientController) EXPECT() *MockPatientControllerMockRecorder {
	return m.recorder
}

// CreatePatient mocks base method.
func (m *MockPatientController) CreatePatient(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreatePatient", ctx)
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientControllerMockRecorder) CreatePatient(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientController)(nil).CreatePatient), ctx)
}

// UpdatePatient mocks base method.
func (m *MockPatientController) UpdatePatient(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePatient", ctx)
}

// UpdatePatient indicates an expected call of UpdatePatient.
func (mr *MockPatientControllerMockRecorder) UpdatePatient(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePatient", reflect.TypeOf((*MockPatientController)(nil).UpdatePatient), ctx)
}
