// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mock/mock_inference_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	inference "aitrics-vital-signs/api-server/domain/inference"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInferenceService is a mock of InferenceService interface.
type MockInferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockInferenceServiceMockRecorder
	isgomock struct{}
}

// MockInferenceServiceMockRecorder is the mock recorder for MockInferenceService.
type MockInferenceServiceMockRecorder struct {
	mock *MockInferenceService
}

// NewMockInferenceService creates a new mock instance.
func NewMockInferenceService(ctrl *gomock.Controller) *MockInferenceService {
	mock := &MockInferenceService{ctrl: ctrl}
	mock.recorder = &MockInferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInferenceService) EXPECT() *MockInferenceServiceMockRecorder {
	return m.recorder
}

// CalculateVitalRisk mocks base method.
func (m *MockInferenceService) CalculateVitalRisk(ctx context.Context, request inference.VitalRiskRequest) (*inference.VitalRiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateVitalRisk", ctx, request)
	ret0, _ := ret[0].(*inference.VitalRiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateVitalRisk indicates an expected call of CalculateVitalRisk.
func (mr *MockInferenceServiceMockRecorder) CalculateVitalRisk(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateVitalRisk", reflect.TypeOf((*MockInferenceService)(nil).CalculateVitalRisk), ctx, request)
}
