// Code generated by MockGen. DO NOT EDIT.
// Source: external.go
//
// Generated by this command:
//
//	mockgen -source=external.go -destination=./mock/mock_external.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockExternalDBClient is a mock of ExternalDBClient interface.
type MockExternalDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockExternalDBClientMockRecorder
	isgomock struct{}
}

// MockExternalDBClientMockRecorder is the mock recorder for MockExternalDBClient.
type MockExternalDBClientMockRecorder struct {
	mock *MockExternalDBClient
}

// NewMockExternalDBClient creates a new mock instance.
func NewMockExternalDBClient(ctrl *gomock.Controller) *MockExternalDBClient {
	mock := &MockExternalDBClient{ctrl: ctrl}
	mock.recorder = &MockExternalDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalDBClient) EXPECT() *MockExternalDBClientMockRecorder {
	return m.recorder
}

// MySQL mocks base method.
func (m *MockExternalDBClient) MySQL() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MySQL")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// MySQL indicates an expected call of MySQL.
func (mr *MockExternalDBClientMockRecorder) MySQL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MySQL", reflect.TypeOf((*MockExternalDBClient)(nil).MySQL))
}
