// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=../mock/mock_vital_controller.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockVitalController is a mock of VitalController interface.
type MockVitalController struct {
	ctrl     *gomock.Controller
	recorder *MockVitalControllerMockRecorder
	isgomock struct{}
}

// MockVitalControllerMockRecorder is the mock recorder for MockVitalController.
type MockVitalControllerMockRecorder struct {
	mock *MockVitalController
}

// NewMockVitalController creates a new mock instance.
func NewMockVitalController(ctrl *gomock.Controller) *MockVitalController {
	mock := &MockVitalController{ctrl: ctrl}
	mock.recorder = &MockVitalControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVitalController) EXPECT() *MockVitalControllerMockRecorder {
	return m.recorder
}

// UpsertVital mocks base method.
func (m *MockVitalController) UpsertVital(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpsertVital", ctx)
}

// UpsertVital indicates an expected call of UpsertVital.
func (mr *MockVitalControllerMockRecorder) UpsertVital(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertVital", reflect.TypeOf((*MockVitalController)(nil).UpsertVital), ctx)
}
