// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=../mock/mock_inference_controller.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockInferenceController is a mock of InferenceController interface.
type MockInferenceController struct {
	ctrl     *gomock.Controller
	recorder *MockInferenceControllerMockRecorder
	isgomock struct{}
}

// MockInferenceControllerMockRecorder is the mock recorder for MockInferenceController.
type MockInferenceControllerMockRecorder struct {
	mock *MockInferenceController
}

// NewMockInferenceController creates a new mock instance.
func NewMockInferenceController(ctrl *gomock.Controller) *MockInferenceController {
	mock := &MockInferenceController{ctrl: ctrl}
	mock.recorder = &MockInferenceControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInferenceController) EXPECT() *MockInferenceControllerMockRecorder {
	return m.recorder
}

// CalculateVitalRisk mocks base method.
func (m *MockInferenceController) CalculateVitalRisk(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CalculateVitalRisk", ctx)
}

// CalculateVitalRisk indicates an expected call of CalculateVitalRisk.
func (mr *MockInferenceControllerMockRecorder) CalculateVitalRisk(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateVitalRisk", reflect.TypeOf((*MockInferenceController)(nil).CalculateVitalRisk), ctx)
}
