// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mock/mock_vital_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	vital "aitrics-vital-signs/api-server/domain/vital"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVitalService is a mock of VitalService interface.
type MockVitalService struct {
	ctrl     *gomock.Controller
	recorder *MockVitalServiceMockRecorder
	isgomock struct{}
}

// MockVitalServiceMockRecorder is the mock recorder for MockVitalService.
type MockVitalServiceMockRecorder struct {
	mock *MockVitalService
}

// NewMockVitalService creates a new mock instance.
func NewMockVitalService(ctrl *gomock.Controller) *MockVitalService {
	mock := &MockVitalService{ctrl: ctrl}
	mock.recorder = &MockVitalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVitalService) EXPECT() *MockVitalServiceMockRecorder {
	return m.recorder
}

// GetVitalsByPatientIDAndDateRange mocks base method.
func (m *MockVitalService) GetVitalsByPatientIDAndDateRange(ctx context.Context, request vital.GetVitalsRequest) (*vital.GetVitalsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVitalsByPatientIDAndDateRange", ctx, request)
	ret0, _ := ret[0].(*vital.GetVitalsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVitalsByPatientIDAndDateRange indicates an expected call of GetVitalsByPatientIDAndDateRange.
func (mr *MockVitalServiceMockRecorder) GetVitalsByPatientIDAndDateRange(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVitalsByPatientIDAndDateRange", reflect.TypeOf((*MockVitalService)(nil).GetVitalsByPatientIDAndDateRange), ctx, request)
}

// UpsertVital mocks base method.
func (m *MockVitalService) UpsertVital(ctx context.Context, request vital.UpsertVitalRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertVital", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertVital indicates an expected call of UpsertVital.
func (mr *MockVitalServiceMockRecorder) UpsertVital(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertVital", reflect.TypeOf((*MockVitalService)(nil).UpsertVital), ctx, request)
}
