// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../mock/mock_vital_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	vital "aitrics-vital-signs/api-server/domain/vital"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockVitalRepository is a mock of VitalRepository interface.
type MockVitalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVitalRepositoryMockRecorder
	isgomock struct{}
}

// MockVitalRepositoryMockRecorder is the mock recorder for MockVitalRepository.
type MockVitalRepositoryMockRecorder struct {
	mock *MockVitalRepository
}

// NewMockVitalRepository creates a new mock instance.
func NewMockVitalRepository(ctrl *gomock.Controller) *MockVitalRepository {
	mock := &MockVitalRepository{ctrl: ctrl}
	mock.recorder = &MockVitalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVitalRepository) EXPECT() *MockVitalRepositoryMockRecorder {
	return m.recorder
}

// CreateVital mocks base method.
func (m *MockVitalRepository) CreateVital(ctx context.Context, model *vital.Vital) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVital", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVital indicates an expected call of CreateVital.
func (mr *MockVitalRepositoryMockRecorder) CreateVital(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVital", reflect.TypeOf((*MockVitalRepository)(nil).CreateVital), ctx, model)
}

// FindVitalByPatientIDAndRecordedAtAndVitalType mocks base method.
func (m *MockVitalRepository) FindVitalByPatientIDAndRecordedAtAndVitalType(ctx context.Context, patientID string, recordedAt time.Time, vitalType string) (*vital.Vital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVitalByPatientIDAndRecordedAtAndVitalType", ctx, patientID, recordedAt, vitalType)
	ret0, _ := ret[0].(*vital.Vital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVitalByPatientIDAndRecordedAtAndVitalType indicates an expected call of FindVitalByPatientIDAndRecordedAtAndVitalType.
func (mr *MockVitalRepositoryMockRecorder) FindVitalByPatientIDAndRecordedAtAndVitalType(ctx, patientID, recordedAt, vitalType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVitalByPatientIDAndRecordedAtAndVitalType", reflect.TypeOf((*MockVitalRepository)(nil).FindVitalByPatientIDAndRecordedAtAndVitalType), ctx, patientID, recordedAt, vitalType)
}

// FindVitalsByPatientIDAndDateRange mocks base method.
func (m *MockVitalRepository) FindVitalsByPatientIDAndDateRange(ctx context.Context, patientID string, from, to time.Time, vitalType string) ([]vital.Vital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVitalsByPatientIDAndDateRange", ctx, patientID, from, to, vitalType)
	ret0, _ := ret[0].([]vital.Vital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVitalsByPatientIDAndDateRange indicates an expected call of FindVitalsByPatientIDAndDateRange.
func (mr *MockVitalRepositoryMockRecorder) FindVitalsByPatientIDAndDateRange(ctx, patientID, from, to, vitalType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVitalsByPatientIDAndDateRange", reflect.TypeOf((*MockVitalRepository)(nil).FindVitalsByPatientIDAndDateRange), ctx, patientID, from, to, vitalType)
}

// UpdateVital mocks base method.
func (m *MockVitalRepository) UpdateVital(ctx context.Context, model *vital.Vital) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVital", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVital indicates an expected call of UpdateVital.
func (mr *MockVitalRepositoryMockRecorder) UpdateVital(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVital", reflect.TypeOf((*MockVitalRepository)(nil).UpdateVital), ctx, model)
}
