// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	patient "aitrics-vital-signs/api-server/domain/patient"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPatientService is a mock of PatientService interface.
type MockPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockPatientServiceMockRecorder
	isgomock struct{}
}

// MockPatientServiceMockRecorder is the mock recorder for MockPatientService.
type MockPatientServiceMockRecorder struct {
	mock *MockPatientService
}

// NewMockPatientService creates a new mock instance.
func NewMockPatientService(ctrl *gomock.Controller) *MockPatientService {
	mock := &MockPatientService{ctrl: ctrl}
	mock.recorder = &MockPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientService) EXPECT() *MockPatientServiceMockRecorder {
	return m.recorder
}

// CreatePatient mocks base method.
func (m *MockPatientService) CreatePatient(ctx context.Context, request patient.CreatePatientRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatient", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientServiceMockRecorder) CreatePatient(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientService)(nil).CreatePatient), ctx, request)
}

// UpdatePatient mocks base method.
func (m *MockPatientService) UpdatePatient(ctx context.Context, patientID string, request patient.UpdatePatientRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePatient", ctx, patientID, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePatient indicates an expected call of UpdatePatient.
func (mr *MockPatientServiceMockRecorder) UpdatePatient(ctx, patientID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePatient", reflect.TypeOf((*MockPatientService)(nil).UpdatePatient), ctx, patientID, request)
}
